version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: demo
      POSTGRES_PASSWORD: demo
      POSTGRES_DB: demo
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    volumes:
      - ./backend:/code
      - ./indexes:/code/indexes
    environment:
      DATABASE_URL: postgresql+psycopg2://demo:demo@db:5432/demo
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  db_data:
